//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF7vikram7.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XF7vikram7.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string App_DisplayName {
            get {
                return ResourceManager.GetString("App_DisplayName", resourceCulture);
            }
        }
        
        public static string App_Alert {
            get {
                return ResourceManager.GetString("App_Alert", resourceCulture);
            }
        }
        
        public static string App_PleaseWait {
            get {
                return ResourceManager.GetString("App_PleaseWait", resourceCulture);
            }
        }
        
        public static string App_NetworkNotAvailable {
            get {
                return ResourceManager.GetString("App_NetworkNotAvailable", resourceCulture);
            }
        }
        
        public static string App_Ok {
            get {
                return ResourceManager.GetString("App_Ok", resourceCulture);
            }
        }
        
        public static string App_Yes {
            get {
                return ResourceManager.GetString("App_Yes", resourceCulture);
            }
        }
        
        public static string App_No {
            get {
                return ResourceManager.GetString("App_No", resourceCulture);
            }
        }
        
        public static string App_Cancel {
            get {
                return ResourceManager.GetString("App_Cancel", resourceCulture);
            }
        }
        
        public static string App_Save {
            get {
                return ResourceManager.GetString("App_Save", resourceCulture);
            }
        }
        
        public static string App_Done {
            get {
                return ResourceManager.GetString("App_Done", resourceCulture);
            }
        }
        
        public static string App_Edit {
            get {
                return ResourceManager.GetString("App_Edit", resourceCulture);
            }
        }
        
        public static string App_SelectImageFrom {
            get {
                return ResourceManager.GetString("App_SelectImageFrom", resourceCulture);
            }
        }
        
        public static string App_PhotoGallery {
            get {
                return ResourceManager.GetString("App_PhotoGallery", resourceCulture);
            }
        }
        
        public static string App_Camera {
            get {
                return ResourceManager.GetString("App_Camera", resourceCulture);
            }
        }
        
        public static string App_CameraNotAvailable {
            get {
                return ResourceManager.GetString("App_CameraNotAvailable", resourceCulture);
            }
        }
        
        public static string App_PhotoGalleryNotAvailable {
            get {
                return ResourceManager.GetString("App_PhotoGalleryNotAvailable", resourceCulture);
            }
        }
        
        public static string App_Error {
            get {
                return ResourceManager.GetString("App_Error", resourceCulture);
            }
        }
        
        public static string App_InvalidPhoneNumberCantCall {
            get {
                return ResourceManager.GetString("App_InvalidPhoneNumberCantCall", resourceCulture);
            }
        }
        
        public static string App_CallFeatureNotAvailable {
            get {
                return ResourceManager.GetString("App_CallFeatureNotAvailable", resourceCulture);
            }
        }
        
        public static string App_InvalidEmailAddresCantEmail {
            get {
                return ResourceManager.GetString("App_InvalidEmailAddresCantEmail", resourceCulture);
            }
        }
        
        public static string App_EmailFeatureNotAvailable {
            get {
                return ResourceManager.GetString("App_EmailFeatureNotAvailable", resourceCulture);
            }
        }
        
        public static string App_InvalidWebsiteURL {
            get {
                return ResourceManager.GetString("App_InvalidWebsiteURL", resourceCulture);
            }
        }
        
        public static string App_OpenURLNotAvailable {
            get {
                return ResourceManager.GetString("App_OpenURLNotAvailable", resourceCulture);
            }
        }
        
        public static string SignUp_EmailAddress {
            get {
                return ResourceManager.GetString("SignUp_EmailAddress", resourceCulture);
            }
        }
        
        public static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        public static string SignUp_Rememberme {
            get {
                return ResourceManager.GetString("SignUp_Rememberme", resourceCulture);
            }
        }
        
        public static string SignUp_ForgotPassword {
            get {
                return ResourceManager.GetString("SignUp_ForgotPassword", resourceCulture);
            }
        }
        
        public static string SignUp_SignIn {
            get {
                return ResourceManager.GetString("SignUp_SignIn", resourceCulture);
            }
        }
        
        public static string SignUp_DontHaveAnAccount {
            get {
                return ResourceManager.GetString("SignUp_DontHaveAnAccount", resourceCulture);
            }
        }
        
        public static string SignUp_SignUp {
            get {
                return ResourceManager.GetString("SignUp_SignUp", resourceCulture);
            }
        }
        
        public static string SignUp_EnterEmailValidation {
            get {
                return ResourceManager.GetString("SignUp_EnterEmailValidation", resourceCulture);
            }
        }
        
        public static string SignUp_EnterPasswordValidation {
            get {
                return ResourceManager.GetString("SignUp_EnterPasswordValidation", resourceCulture);
            }
        }
        
        public static string SignUp_InvalidCredentials {
            get {
                return ResourceManager.GetString("SignUp_InvalidCredentials", resourceCulture);
            }
        }
        
        public static string ForgotPassword_PleaseEnterEmailText {
            get {
                return ResourceManager.GetString("ForgotPassword_PleaseEnterEmailText", resourceCulture);
            }
        }
        
        public static string ForgotPassword_EmailAddress {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailAddress", resourceCulture);
            }
        }
        
        public static string ForgotPassword_ResetPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_ResetPassword", resourceCulture);
            }
        }
        
        public static string ForgotPassword_EnterEmailValidation {
            get {
                return ResourceManager.GetString("ForgotPassword_EnterEmailValidation", resourceCulture);
            }
        }
        
        public static string ForgotPassword_EmailSentToResetPassword {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailSentToResetPassword", resourceCulture);
            }
        }
        
        public static string ForgotPassword_EmailNotFound {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailNotFound", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_CREATEACCOUNTCAPS {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_CREATEACCOUNTCAPS", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_WeWillProvideAText {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_WeWillProvideAText", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_AccountInformation {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_AccountInformation", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_EmailAddress {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_EmailAddress", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_Password {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_Password", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_CreateAccount {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_CreateAccount", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_EnterEmailValidation {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_EnterEmailValidation", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_EnterPasswordValidation {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_EnterPasswordValidation", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_PasswordNotMatchingValidation {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_PasswordNotMatchingValidation", resourceCulture);
            }
        }
        
        public static string SignUpCreateAccount_EmailAlreadyPresent {
            get {
                return ResourceManager.GetString("SignUpCreateAccount_EmailAlreadyPresent", resourceCulture);
            }
        }
        
        public static string LeftMenuMaster_Home {
            get {
                return ResourceManager.GetString("LeftMenuMaster_Home", resourceCulture);
            }
        }
        
        public static string LeftMenuMaster_Notifications {
            get {
                return ResourceManager.GetString("LeftMenuMaster_Notifications", resourceCulture);
            }
        }
        
        public static string LeftMenuMaster_Logout {
            get {
                return ResourceManager.GetString("LeftMenuMaster_Logout", resourceCulture);
            }
        }
        
        public static string LeftMenuMaster_FailedToLogUserOut {
            get {
                return ResourceManager.GetString("LeftMenuMaster_FailedToLogUserOut", resourceCulture);
            }
        }
        
        public static string Account_ACCOUNT {
            get {
                return ResourceManager.GetString("Account_ACCOUNT", resourceCulture);
            }
        }
        
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        public static string Account_ContactInformation {
            get {
                return ResourceManager.GetString("Account_ContactInformation", resourceCulture);
            }
        }
        
        public static string Account_NAME {
            get {
                return ResourceManager.GetString("Account_NAME", resourceCulture);
            }
        }
        
        public static string Account_EMAIL {
            get {
                return ResourceManager.GetString("Account_EMAIL", resourceCulture);
            }
        }
        
        public static string Account_PHONENUMBER {
            get {
                return ResourceManager.GetString("Account_PHONENUMBER", resourceCulture);
            }
        }
        
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        public static string Account_OLDPASSWORD {
            get {
                return ResourceManager.GetString("Account_OLDPASSWORD", resourceCulture);
            }
        }
        
        public static string Account_NEWPASSWORD {
            get {
                return ResourceManager.GetString("Account_NEWPASSWORD", resourceCulture);
            }
        }
        
        public static string Account_CONFIRMPASSWORD {
            get {
                return ResourceManager.GetString("Account_CONFIRMPASSWORD", resourceCulture);
            }
        }
        
        public static string Account_Confirm {
            get {
                return ResourceManager.GetString("Account_Confirm", resourceCulture);
            }
        }
        
        public static string Account_EnterOldPassword {
            get {
                return ResourceManager.GetString("Account_EnterOldPassword", resourceCulture);
            }
        }
        
        public static string Account_EnterNewPassword {
            get {
                return ResourceManager.GetString("Account_EnterNewPassword", resourceCulture);
            }
        }
        
        public static string Account_EnterConfirmPassword {
            get {
                return ResourceManager.GetString("Account_EnterConfirmPassword", resourceCulture);
            }
        }
        
        public static string Account_NewPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("Account_NewPasswordDoNotMatch", resourceCulture);
            }
        }
        
        public static string Account_ChangePasswordSuccessful {
            get {
                return ResourceManager.GetString("Account_ChangePasswordSuccessful", resourceCulture);
            }
        }
        
        public static string Account_ChangePasswordFailed {
            get {
                return ResourceManager.GetString("Account_ChangePasswordFailed", resourceCulture);
            }
        }
        
        public static string Notifications_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("Notifications_NOTIFICATIONS", resourceCulture);
            }
        }
        
        public static string Notifications_All {
            get {
                return ResourceManager.GetString("Notifications_All", resourceCulture);
            }
        }
    }
}
